-- ggt_prod.locations definition

CREATE TABLE `locations` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `site_code` varchar(45) NOT NULL DEFAULT 'GGT',
  `org_id` int(11) NOT NULL DEFAULT '1',
  `name` varchar(255) DEFAULT NULL,
  `addr1` varchar(1000) DEFAULT NULL,
  `addr2` varchar(45) DEFAULT NULL,
  `addr3` varchar(45) DEFAULT NULL,
  `city` varchar(45) DEFAULT NULL,
  `st` varchar(10) DEFAULT 'TX',
  `zip` varchar(12) DEFAULT NULL,
  `lat` float(10,6) DEFAULT NULL,
  `lng` float(10,6) DEFAULT NULL,
  `time_zone` varchar(45) DEFAULT 'CST',
  `time_zone_offset` varchar(45) DEFAULT '-05:00',
  `test_type_offered` enum('oral','nasal','oral_fluid','unknown') DEFAULT 'oral',
  `status` enum('enabled','disabled') DEFAULT 'enabled',
  `type` enum('drive_thru','walk_up','drive_thru_and_walk_up','unknown') DEFAULT 'drive_thru',
  `billing_type` enum('client_bill','insurance','client_bill_and_insurance','unknown') DEFAULT 'client_bill',
  `collect_insurance_info` tinyint(4) NOT NULL DEFAULT '1',
  `allow_insurance_skip` tinyint(4) NOT NULL DEFAULT '1',
  `collect_upfront_payment` tinyint(4) NOT NULL DEFAULT '0',
  `image_thumbnail` mediumtext,
  `accepts_bookings` tinyint(4) DEFAULT NULL,
  `accepts_walkins` tinyint(4) DEFAULT NULL,
  `operator` varchar(45) DEFAULT NULL,
  `phone_number` varchar(45) DEFAULT NULL,
  `website` varchar(255) DEFAULT NULL,
  `open_hours` varchar(255) DEFAULT NULL,
  `misc` varchar(255) DEFAULT NULL,
  `is_external` tinyint(4) NOT NULL DEFAULT '0',
  `lab_id` int(11) NOT NULL DEFAULT '1',
  `create_dt` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_dt` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `site_code_ix` (`site_code`),
  KEY `status` (`status`),
  KEY `city_ix` (`city`),
  KEY `lat_ix` (`lat`),
  KEY `lng_ix` (`lng`),
  KEY `st_ix` (`st`),
  KEY `zip_ix` (`zip`),
  KEY `time_zone_ix` (`time_zone`),
  KEY `test_type_ix` (`test_type_offered`),
  KEY `billing_type_ix` (`billing_type`)
) ENGINE=InnoDB AUTO_INCREMENT=2642 DEFAULT CHARSET=utf8;