-- ggt_prod.patient_questionnaires definition

CREATE TABLE `patient_questionnaires` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `patient_id` int(11) DEFAULT NULL,
  `token` varchar(45) DEFAULT NULL,
  `group_code` varchar(45) DEFAULT NULL,
  `symptom_fever` tinyint(4) DEFAULT NULL,
  `symptom_shortness_breath` tinyint(4) DEFAULT NULL,
  `symptom_cough` tinyint(4) DEFAULT NULL,
  `symptom_chest_pain` tinyint(4) DEFAULT NULL,
  `symptom_lack_of_smell` tinyint(4) DEFAULT NULL,
  `symptom_other_breathing` tinyint(4) DEFAULT NULL,
  `covid_contact` tinyint(4) DEFAULT NULL,
  `prescription_use` tinyint(4) DEFAULT NULL,
  `heart_disease` tinyint(4) DEFAULT NULL,
  `diabetes` tinyint(4) DEFAULT NULL,
  `respiratory_diseases` tinyint(4) DEFAULT NULL,
  `autoimmune_disease` tinyint(4) DEFAULT NULL,
  `other_chronic` tinyint(4) DEFAULT NULL,
  `allergies` tinyint(4) DEFAULT NULL,
  `consent_signature` varchar(45) DEFAULT NULL,
  `consent_date` datetime DEFAULT CURRENT_TIMESTAMP,
  `insurance_details` varchar(45) DEFAULT NULL,
  `has_insurance_photo` tinyint(4) DEFAULT NULL,
  `is_patient` tinyint(4) DEFAULT NULL,
  `provider_consent_signature` varchar(45) DEFAULT NULL,
  `provider_consent_custom_field_1` varchar(255) DEFAULT NULL,
  `provider_consent_custom_field_2` varchar(255) DEFAULT NULL,
  `provider_consent_custom_field_3` varchar(255) DEFAULT NULL,
  `influenza_consent_signature` varchar(45) DEFAULT NULL,
  `public_places_bars_restaurants_cafes` tinyint(4) DEFAULT NULL,
  `public_places_gas_stations` tinyint(4) DEFAULT NULL,
  `public_places_medical_offices` tinyint(4) DEFAULT NULL,
  `public_places_place_of_work` tinyint(4) DEFAULT NULL,
  `public_places_retail_grocery_stores` tinyint(4) DEFAULT NULL,
  `public_places_places_of_worship` tinyint(4) DEFAULT NULL,
  `public_places_public_parks` tinyint(4) DEFAULT NULL,
  `public_places_other` tinyint(4) DEFAULT NULL,
  `service_covid19_test` tinyint(4) DEFAULT NULL,
  `service_flu_shot` tinyint(4) DEFAULT NULL,
  `service_consult` tinyint(4) DEFAULT NULL,
  `flu_screen_severely_ill` tinyint(4) DEFAULT NULL,
  `flu_screen_guillain_barre_syndrome` tinyint(4) DEFAULT NULL,
  `flu_screen_life_threatening_reaction` tinyint(4) DEFAULT NULL,
  `flu_screen_egg_allergy` tinyint(4) DEFAULT NULL,
  `symptoms_vax` tinyint(4) DEFAULT NULL,
  `pregnancy` tinyint(4) DEFAULT NULL,
  `allergic_reaction` tinyint(4) DEFAULT NULL,
  `covid19_confirmed_case` tinyint(4) DEFAULT NULL,
  `egg_allergy` tinyint(4) DEFAULT NULL,
  `guillian_barre` tinyint(4) DEFAULT NULL,
  `create_dt` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_dt` datetime DEFAULT CURRENT_TIMESTAMP,
  `recent_vaccinations` tinyint(4) DEFAULT NULL,
  `blood_transfusion` tinyint(4) DEFAULT NULL,
  `nervous_system` tinyint(4) DEFAULT NULL,
  `immune_system_medications` tinyint(4) DEFAULT NULL,
  `immune_system` tinyint(4) DEFAULT NULL,
  `long_term_health` tinyint(4) DEFAULT NULL,
  `ggv_allergies` tinyint(4) DEFAULT NULL,
  `serious_reaction` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `patient_id_ix` (`patient_id`),
  KEY `token_ix` (`token`),
  KEY `group_code_ix` (`group_code`),
  KEY `insurance_photo_ix` (`has_insurance_photo`)
) ENGINE=InnoDB AUTO_INCREMENT=590633 DEFAULT CHARSET=utf8;