-- ggt_prod.patients definition

CREATE TABLE `patients` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `first_name` varchar(45) DEFAULT NULL,
  `middle_name` varchar(45) DEFAULT NULL,
  `last_name` varchar(45) DEFAULT NULL,
  `gender` enum('male','female','unknown') DEFAULT NULL,
  `height_ft` varchar(45) DEFAULT NULL,
  `height_in` varchar(45) DEFAULT NULL,
  `weight_lb` varchar(45) DEFAULT NULL,
  `ethnicity` varchar(45) DEFAULT NULL,
  `race` varchar(45) DEFAULT NULL,
  `addr1` varchar(45) DEFAULT NULL,
  `addr2` varchar(45) DEFAULT NULL,
  `addr3` varchar(45) DEFAULT NULL,
  `city` varchar(45) DEFAULT NULL,
  `county` varchar(45) DEFAULT NULL,
  `st` varchar(45) DEFAULT NULL,
  `zip` varchar(45) DEFAULT NULL,
  `dob` date DEFAULT NULL,
  `phone_number` varchar(45) DEFAULT NULL,
  `phone_number_verified` varchar(45) DEFAULT NULL,
  `email` varchar(45) DEFAULT NULL,
  `email_verified` varchar(45) DEFAULT NULL,
  `token` varchar(45) DEFAULT NULL,
  `result_token` varchar(45) DEFAULT NULL,
  `token_expire` datetime DEFAULT CURRENT_TIMESTAMP,
  `create_dt` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_dt` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `ix_token` (`token`),
  KEY `ix_create_dt` (`create_dt`),
  KEY `ix_gender` (`gender`),
  KEY `ix_ethnicity` (`ethnicity`),
  KEY `ix_race` (`race`),
  KEY `ix_city` (`city`),
  KEY `ix_st` (`st`),
  KEY `ix_zip` (`zip`),
  KEY `ix_dob` (`dob`),
  FULLTEXT KEY `ix_first_name` (`first_name`),
  FULLTEXT KEY `ix_email` (`email`),
  FULLTEXT KEY `ix_last_name` (`last_name`),
  FULLTEXT KEY `ix_middle_name` (`middle_name`),
  FULLTEXT KEY `ix_phone_number` (`phone_number`)
) ENGINE=InnoDB AUTO_INCREMENT=838423 DEFAULT CHARSET=utf8;