image: python:3.7.2

pipelines:
  branches:
######################################################## GCP DEPLOYMENTS ###############################################

    production-patient-aws:
      - step:
          name: Patient AWS Fargate Deployemrnt
          services:
            - docker
          caches:
            - pip
          script:
            - cp app/ggt/configs/config-prod.yml app/ggt/configs/config.yml
            - cp app/ggt/configs/log-config-prod.yml app/ggt/configs/log-config.yml
            - cp app/ggt/configs/gcp-service-account-prod.json app/ggt/configs/gcp-service-account.json
            - pip3 install awscli
            - aws configure set aws_access_key_id "${AWS_KEY}"
            - aws configure set aws_secret_access_key "${AWS_SECRET}"
            - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 135292740376.dkr.ecr.us-east-2.amazonaws.com
            - docker build -t ggt-api .
            - docker tag ggt-api:latest 135292740376.dkr.ecr.us-east-2.amazonaws.com/ggt-api:latest
            - docker push 135292740376.dkr.ecr.us-east-2.amazonaws.com/ggt-api:latest
            - aws ecs update-service --region us-east-2 --cluster ggt-api --service ggt-api-1 --force-new-deployment
            - aws ecs update-service --region us-west-2 --cluster portal-prod-us-west-2-cluster --service portal-prod-us-west-2-service --force-new-deployment

    dev:
      - step:
          name: DEV Testing
          image: python:3.7.9
          caches:
            - pip
          artifacts:
            - pytest-logs.txt
          script:
            - cp app/ggt/configs/config-dev.yml app/ggt/configs/config.yml
            - cp app/ggt/configs/log-config-dev.yml app/ggt/configs/log-config.yml
            - cp app/ggt/configs/gcp-service-account-dev.json app/ggt/configs/gcp-service-account.json
            - apt-get update && apt-get -y install gcc
            - pip install pipenv
            - pipenv lock --requirements
            - pipenv lock --requirements > app/requirements.txt
            - pip install --no-cache-dir -r app/requirements.txt
            - pytest -vs
      - step:
          name: Development Deployment
          deployment: staging
          caches:
            - docker
          script:
            - cp app/ggt/configs/config-dev.yml app/ggt/configs/config.yml
            - cp app/ggt/configs/log-config-dev.yml app/ggt/configs/log-config.yml
            - cp app/ggt/configs/gcp-service-account-dev.json app/ggt/configs/gcp-service-account.json
            - pip3 install awscli
            - aws configure set aws_access_key_id "${AWS_KEY}"
            - aws configure set aws_secret_access_key "${AWS_SECRET}"
            - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 135292740376.dkr.ecr.us-east-2.amazonaws.com
            - docker build -t ggt-api:dev .
            - docker tag ggt-api:dev 135292740376.dkr.ecr.us-east-2.amazonaws.com/ggt-api:dev
            - docker push 135292740376.dkr.ecr.us-east-2.amazonaws.com/ggt-api:dev
            - aws ecs update-service --region us-east-2 --cluster ggt-api-dev --service ggt-api-dev --force-new-deployment

    qa:
      - step:
          name: QA Deployment
          deployment: staging
          caches:
            - docker
          script:
            - cp app/ggt/configs/config-qa.yml app/ggt/configs/config.yml
            - cp app/ggt/configs/log-config-qa.yml app/ggt/configs/log-config.yml
            - cp app/ggt/configs/gcp-service-account-qa.json app/ggt/configs/gcp-service-account.json
            - pip3 install awscli
            - aws configure set aws_access_key_id "${AWS_KEY}"
            - aws configure set aws_secret_access_key "${AWS_SECRET}"
            - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 135292740376.dkr.ecr.us-east-2.amazonaws.com
            - docker build -t ggt-api:qa .
            - docker tag ggt-api:qa 135292740376.dkr.ecr.us-east-2.amazonaws.com/ggt-api:qa
            - docker push 135292740376.dkr.ecr.us-east-2.amazonaws.com/ggt-api:qa
            - aws ecs update-service --region us-east-2 --cluster ggt-api-qa --service ggt-api-qa --force-new-deployment

    dev2:
      - step:
          name: DEV2 Deployment
          deployment: staging
          caches:
            - docker
          script:
            - cp app/ggt/configs/config-dev2.yml app/ggt/configs/config.yml
            - cp app/ggt/configs/log-config-dev2.yml app/ggt/configs/log-config.yml
            - cp app/ggt/configs/gcp-service-account-dev2.json app/ggt/configs/gcp-service-account.json
            - pip3 install awscli
            - aws configure set aws_access_key_id "${AWS_KEY}"
            - aws configure set aws_secret_access_key "${AWS_SECRET}"
            - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 135292740376.dkr.ecr.us-east-2.amazonaws.com
            - docker build -t ggt-api:dev2 .
            - docker tag ggt-api:dev2 135292740376.dkr.ecr.us-east-2.amazonaws.com/ggt-api:dev2
            - docker push 135292740376.dkr.ecr.us-east-2.amazonaws.com/ggt-api:dev2
            - aws ecs update-service --region us-east-2 --cluster ggt-api-dev --service ggt-api-dev2 --force-new-deployment

    production-portal:
      - step:
          name: PROD PORTAL Deployment
          deployment: staging
          caches:
            - docker
          script:
            - cp app/ggt/configs/config-prod.yml app/ggt/configs/config.yml
            - cp app/ggt/configs/log-config-prod.yml app/ggt/configs/log-config.yml
            - cp app/ggt/configs/gcp-service-account-prod.json app/ggt/configs/gcp-service-account.json
            - pip3 install awscli
            - aws configure set aws_access_key_id "${AWS_KEY}"
            - aws configure set aws_secret_access_key "${AWS_SECRET}"
            - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 135292740376.dkr.ecr.us-east-2.amazonaws.com
            - docker build -t ggt-api:portal .
            - docker tag ggt-api:portal 135292740376.dkr.ecr.us-east-2.amazonaws.com/ggt-api:portal
            - docker push 135292740376.dkr.ecr.us-east-2.amazonaws.com/ggt-api:portal
            - #aws ecs update-service --region us-east-2 --cluster ggt-api --service ggt-api-portal --force-new-deployment
            - aws ecs update-service --region us-west-2 --cluster portal-prod-us-west-2-cluster --service portal-prod-us-west-2-service --force-new-deployment

    production-ops:
      - step:
          name: PROD OPS Deployment
          deployment: staging
          caches:
            - docker
          script:
            - cp app/ggt/configs/config-prod.yml app/ggt/configs/config.yml
            - cp app/ggt/configs/log-config-prod.yml app/ggt/configs/log-config.yml
            - cp app/ggt/configs/gcp-service-account-prod.json app/ggt/configs/gcp-service-account.json
            - pip3 install awscli
            - aws configure set aws_access_key_id "${AWS_KEY}"
            - aws configure set aws_secret_access_key "${AWS_SECRET}"
            - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 135292740376.dkr.ecr.us-east-2.amazonaws.com
            - docker build -t ggt-api:ops .
            - docker tag ggt-api:ops 135292740376.dkr.ecr.us-east-2.amazonaws.com/ggt-api:ops
            - docker push 135292740376.dkr.ecr.us-east-2.amazonaws.com/ggt-api:ops
            - aws ecs update-service --region us-west-2 --cluster ops-prod-us-west-2-cluster --service ops-prod-us-west-2-service --force-new-deployment
            - #aws ecs update-service --region us-east-2 --cluster ggt-api --service ggt-api-ops --force-new-deployment



options:
  docker: true
