image: python:3.7.2

pipelines:
  branches:
    master:
      - step:
          name: Deployment
          image: google/cloud-sdk:latest
          caches:
            - docker
          script:
            - pipenv lock --requirements > app/requirements.txt
            - cp app/ggt/configs/config-dev2.yml app/ggt/configs/config.yml

  options:
  docker: trueID: dev2