app_name: ggt-api
app_version: 1.1
log_level: DEBUG
base_url: https://start-dev.GoGetTested.com
env: DEV
default_timezone: CST

server:
  host: 0.0.0.0
  port: 8888
  inbound_processor_port: 5010
  outbound_processor_port: 5020
  email_queue_processor_port: 5030
  sms_queue_processor_port: 5040

origins: 
  - https://gogettested.com
  - https://schedule.gogettested.com
  - https://start.gogettested.com
  - https://start-dev.gogettested.com
  - https://start-qa.gogettested.com
  - https://portal.gogettested.com
  - https://portal-dev.gogettested.com
  - https://portal-qa.gogettested.com
  - https://ops.gogettested.com
  - https://ops-dev.gogettested.com
  - https://ops-qa.gogettested.com
  - http://localhost
  - http://localhost:3000
  - http://localhost:5000
  - http://localhost:8000

docs:
  swagger_url: /docs
  redoc_url: /redoc

aws:
  region: us-east-1
  access_key_id: AKIAR7AATMMMGKHVWYP6
  secret_access_key: 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
  sqs_print_queue_base_url: https://sqs.us-east-1.amazonaws.com/135292740376/ggt-print-queue

gcp:
  project_id: ggt-pfe-dev
  service_account_file: gcp-service-account.json
  default_link_expiration_time_limit: 300
  service_account_file_prod: gcp-service-account-prod.json
  all_inbound_files_bucket_name: ggt-all-inbound-files-prod
  lab_reports_bucket_name: ggt-lab-reports-prod
  insurance_cards_bucket_name: ggt-insurance-cards-prod
  notification_archive_bucket_name: ggt-notification-archive-dev
  enable_cloud_profiler: false
  enable_cloud_logger: false
  cloud_logger_log_level: 3 # 0-error, 1-warning, 2-info, 3-debug. 

databases:
  mysql:
    host: prod-ggt-aurora.cluster-csfqhv5lbvg2.us-east-2.rds.amazonaws.com
    read_replica_host: prod-ggt-aurora.cluster-ro-csfqhv5lbvg2.us-east-2.rds.amazonaws.com
    username: admin
    password: hWMgl5Tfkqn30saQNp9M
    db: ggt_prod

  sqlite:
    tasks_sqlite_db: /Users/suresh/ggt-tasks/ggt_tasks_local_cache.db

notifications:
  from_email: support@gogettested.com
  from_name: Go Get Tested
  confirmation_subject: '{{first_name}}, Your Covid-19 test has been scheduled'
  result_subject: COVID-19 Testing Result Available
  appointment_reminder_sublect: GoGetTested COVID-19 Testing Appointment Reminder
  relocate_subject: COVID-19 Testing Appointment has Changed
  reschedule_subject: COVID-19 Testing Appointment is Re-Scheduled
  confirmation_template: GGT-1-APPOINTMENT-CONFIRMATION-EMAIL.html.html
  result_template: GGT-5-RESULT-AVAILABLE-EMAIL.html
  appointment_reminder_template: GGT-2-APPOINTMENT-REMINDER.html
  relocate_template: GGT-7-APPOINTMENT-RESCHEDULE-EMAIL.html
  reschedule_template: GGT-8-APPOINTMENT-RESCHEDULE-2-EMAIL.html

twilio:
  account_sid: AC9cef9b4155030ee2683281ccc72d4001
  auth_token: 62ee76165984c54f91ee80aac9cb3f0e
  from_number: '+18772802151'

sendgrid:
  sendgrid_api_key: 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

google:
  maps:
    api_key: AIzaSyBJmU3ueSBRmXz4mU1MRgdOxAWcfImbQNQ
    base_url: https://maps.googleapis.com/maps/api/staticmap
    geo_url: https://maps.googleapis.com/maps/api/geocode/json
    zoom_level: 10
    map_type: roadmap
    thumbnail_size: 110x110
    markers_color: red
    markers_size: tiny

email:
  template_folder: /templates/email/

app:
  roles:
    admin: Super Admin
    site_admin: Site Admin
    clinical_provider: Clinical Provider
    care_provider: Care Provider
    contact_center: Contact Center

vendors:
  auth0:
    auth0_domain: gogettested.us.auth0.com
    api_audience: https://role-base-auth.test/api
    algorithms: ['RS256']
    roles: http://roles.ggt/roles

  healthtrackrx_outbound:
    hostname: sftp.healthtrackrx.com
    username: wellpay
    password: 9cTE3fh@8H
    port: 22
    remote_downloads_folder: /Reports
    remote_insurance_images_path: /insurance_files
    remote_backups_path: /backups
    remote_processed_orders_path: /processed_order_files
    local_download_path: /Users/suresh/ggt-tasks/downloads
    local_outbound_file_path: /Users/suresh/ggt-tasks/outbound
    local_insurance_card_file_path: /Users/suresh/ggt-tasks/insurance_images
    local_process_summary_path: /Users/suresh/ggt-tasks/process_summary
    local_backups_path: /Users/suresh/ggt-tasks/backups
    outbound_file_prefix: ggt-outbound

  healthtrackrx_inbound:
    hostname: sftp.gogettested.com
    username: healthtrackrx
    password: q-5QXfKMLR\dtM_c
    port: 22
    remote_downloads_folder: /ggt-sftp/healthtrackrx/Reports
    remote_insurance_images_path: /ggt-sftp/healthtrackrx/insurance_files
    remote_backups_path: /ggt-sftp/healthtrackrx/backups
    remote_processed_orders_path: /ggt-sftp/healthtrackrx/processed_order_files
    local_download_path: /Users/suresh/ggt-tasks/downloads
    local_outbound_file_path: /Users/suresh/ggt-tasks/outbound
    local_insurance_card_file_path: /Users/suresh/ggt-tasks/insurance_images
    local_process_summary_path: /Users/suresh/ggt-tasks/process_summary
    local_backups_path: /Users/suresh/ggt-tasks/backups
    outbound_file_prefix: ggt-outbound

  wellpay:
    endpoint: https://api-staging.getwellpay.com/api/public/v1
    auth_user: suresh@wellpay.com
    auth_password: 8,tp{Na{76<~@.>(

  kdhe:
    hostname: sl64.endpoint.com
    username: sftpwellhealth
    password: s4Ezq$oNf3PV*pVL
    port: 22
    path: /SFTP_CSV/WellHealth_Input_Folder_Prod

  slack:
    slack_token: xoxb-my-bot-token
    slack_channel: '#my-channel'
    slack_icon_url: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuGqps7ZafuzUsViFGIremEL2a3NR0KO0s0RTCMXmzmREJd5m4MA&s
    slack_user_name: Double Images Monitor

pfe:
  signup:
    special_phone_1: '+14158888888'
    special_phone_2: '+14159999999'
    special_phone_3: '4158888888'
    special_phone_4: '4159999999'
    override_otp_code: '000000'
