app_name: ggt-api
app_version: 1.1
log_level: DEBUG
base_url: https://start-dev.GoGetTested.com
portal_url: https://portal-dev.gogettested.com
ops_url: https://ops-dev.gogettested.com
env: DEV
default_timezone: CST

server:
  host: 0.0.0.0
  port: 8888
  inbound_processor_port: 5010
  outbound_processor_port: 5020
  email_queue_processor_port: 5030
  sms_queue_processor_port: 5040

origins: 
  - https://gogettested.com
  - https://schedule.gogettested.com
  - https://start.gogettested.com
  - https://start-dev.gogettested.com
  - https://start-qa.gogettested.com
  - https://portal.gogettested.com
  - https://portal-dev.gogettested.com
  - https://portal-qa.gogettested.com
  - https://ops.gogettested.com
  - https://ops-dev.gogettested.com
  - https://ops-qa.gogettested.com
  - https://gogetvax.com
  - https://ops.gogetvax.com
  - https://ops-dev.gogetvax.com
  - https://ops-qa.gogetvax.com
  - https://portal.gogetvax.com
  - https://portal-dev.gogetvax.com
  - https://portal-qa.gogetvax.com
  - https://start.gogetvax.com
  - https://start-dev.gogetvax.com
  - https://start-qa.gogetvax.com
  - https://schedule.gogetvax.com
  - https://gogetdoc.com
  - https://ops.gogetdoc.com
  - https://ops-dev.gogetdoc.com
  - https://ops-qa.gogetdoc.com
  - https://portal.gogetdoc.com
  - https://portal-dev.gogetdoc.com
  - https://portal-qa.gogetdoc.com
  - https://start.gogetdoc.com
  - https://start-dev.gogetdoc.com
  - https://start-qa.gogetdoc.com
  - https://schedule.gogetdoc.com
  - http://localhost
  - http://localhost:3000
  - http://localhost:5000
  - http://localhost:8000
  - https://vaxyes-ops.gogetvax.com

docs:
  swagger_url: /docs
  redoc_url: /redoc

aws:
  dynamo_table_name: available_slots
  sqs_region: us-east-2
  queue_count: 2
  sqs_url:  https://sqs.us-east-2.amazonaws.com/135292740376/available_slot_queue_dev
  vax_sms_que: https://sqs.us-east-2.amazonaws.com/135292740376/vax_scheduled_sms_notification_queue
  region: us-east-2
  access_key_id: AKIAR7AATMMMGKHVWYP6
  secret_access_key: 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
  sqs_print_queue_base_url: https://sqs.us-east-1.amazonaws.com/135292740376/ggt-print-queue
  lab_reports_bucket_name: ggt-labreports
  default_link_expiration_time_limit: 300
  ggt_ops_images: ggt-ops-images-dev
  vax_certificate_bucket: ggt-vax-certificates-dev
  
gcp:
  project_id: ggt-pfe-dev
  service_account_file: gcp-service-account.json
  default_link_expiration_time_limit: 300
  service_account_file_prod: gcp-service-account-prod.json
  all_inbound_files_bucket_name: ggt-all-inbound-files-prod
  lab_reports_bucket_name: ggt-lab-reports-prod
  insurance_cards_bucket_name: ggt-insurance-cards-prod
  notification_archive_bucket_name: ggt-notification-archive-dev
  enable_cloud_profiler: false
  enable_cloud_logger: false
  cloud_logger_log_level: 3 # 0-error, 1-warning, 2-info, 3-debug.


databases:
  mysql:
    host: ggt-dev-db.cluster-csfqhv5lbvg2.us-east-2.rds.amazonaws.com
    read_replica_host: ggt-dev-db.cluster-ro-csfqhv5lbvg2.us-east-2.rds.amazonaws.com
    username: admin
    password: hWMgl5Tfkqn30saQNp9M
    db: ggt_prod


  sqlite:
    tasks_sqlite_db: /Users/suresh/ggt-tasks/ggt_tasks_local_cache.db

notifications:
  from_email: support@gogettested.com
  from_name: Go Get Tested
  confirmation_subject: '{{first_name}}, {{subject_test_scheduled}}'
  result_subject: COVID-19 Testing Result Available
  appointment_reminder_sublect: GoGetTested COVID-19 Testing Appointment Reminder
  relocate_subject: COVID-19 Testing Appointment has Changed
  reschedule_subject: COVID-19 Testing Appointment is Re-Scheduled
  confirmation_template: GGT-1-APPOINTMENT-CONFIRMATION-EMAIL.html
  result_template: GGT-5-RESULT-AVAILABLE-EMAIL.html
  appointment_reminder_template: GGT-2-APPOINTMENT-REMINDER.html
  relocate_template: GGT-7-APPOINTMENT-RESCHEDULE-EMAIL.html
  reschedule_template: GGT-8-APPOINTMENT-RESCHEDULE-2-EMAIL.html
  confirmation_template_ggv: GGV-1-APPOINTMENT-CONFIRMATION-EMAIL.html
  confirmation_subject_ggv: '{{first_name}}, Your Covid-19 vaccination has been scheduled'
  hide_phone_number_in_countries: MX # comma separated values

twilio:
  account_sid: AC9cef9b4155030ee2683281ccc72d4001
  auth_token: 62ee76165984c54f91ee80aac9cb3f0e
  from_number: "+18772802151"
  account_sid_short_code: ACa718334f24171c002bc3ee69c59aae9e
  auth_token_short_code: e9a391c21722705f3c7902fcde7522a4
  from_number_short_code: "80578"
  from_number_to_call: "+16504378296"
sendgrid:
  sendgrid_api_key: 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

google:
  maps:
    api_key: AIzaSyBH2PDb_3WMu7MxHpG5DlwZ66PyJ0rv5aQ
    base_url: https://maps.googleapis.com/maps/api/staticmap
    geo_url: https://maps.googleapis.com/maps/api/geocode/json
    zoom_level: 10
    map_type: roadmap
    thumbnail_size: 110x110
    markers_color: red
    markers_size: tiny

email:
  template_folder: /templates/email/

app:
  roles:
    admin: Super Admin
    site_admin: Site Admin
    clinical_provider: Clinical Provider
    care_provider: Care Provider
    contact_center: Contact Center

vendors:
  auth0:
    auth0_domain: gogettested.us.auth0.com
    api_audience: https://role-base-auth.test/api
    algorithms: ["RS256"]
    roles: http://roles.ggt/roles
    management_client_id: 6ok7VWNkeOA6An5sN30Jl9gHoH4oUT8j
    management_sectret: Rwx8-mby99m5O-2aR14JKgoim0VV0FJuO6sefpDxXjKiQ18mys4JWf2oAO6_5Mha
    connection: Username-Password-Authentication

  healthtrackrx:
    ggt_api:
      api_key_name: x-api-key
      api_key_value: f63e3e17-e10a-4f57-b7b5-08a40d4b0d6b
    inbound:
      local_download_path: /Users/suresh/ggt-tasks/downloads/healthtrackrx/Reports  
      local_backups_path: /Users/suresh/ggt-tasks/backups
    outbound:
      outbound_file_prefix: ggt-outbound
      local_outbound_file_path: /Users/suresh/ggt-tasks/outbound
      local_insurance_card_file_path: /Users/suresh/ggt-tasks/insurance_images

  mawdpath:
    inbound:
      remote_downloads_folder: /ggt-sftp/mawdpath/results
      remote_processed_orders_path: /ggt-sftp/mawdpath/results/archived
    outbound:
      outbound_file_prefix: ggt-outbound-mawd

  wellpay:
    endpoint: https://api-staging.getwellpay.com/api/public/v1
    auth_user: suresh@wellpay.com
    auth_password: 8,tp{Na{76<~@.>(
    npi: 1780944496

  kdhe:
    hostname: sl64.endpoint.com
    username: sftpwellhealth
    password: s4Ezq$oNf3PV*pVL
    port: 22
    path: /SFTP_CSV/WellHealth_Input_Folder_Prod

  slack:
    slack_token: xoxb-my-bot-token
    slack_channel: "#my-channel"
    slack_icon_url: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuGqps7ZafuzUsViFGIremEL2a3NR0KO0s0RTCMXmzmREJd5m4MA&s
    slack_user_name: Double Images Monitor

pfe:
  signup:
    special_phone_1: "+14158888888"
    special_phone_2: "+14159999999"
    special_phone_3: "4158888888"
    special_phone_4: "4159999999"
    override_otp_code: "000000"


security:
  ggv_secret: "thisistheggvtopsecret2021"

payment:
  stripe:
    secret_key: "sk_test_51IRhpxAf0ltvHUzx80AaXczh8OjQWDEhRJmqdugww38vmUPBmDeOlRRWlU0QMgxB5bSy3X6vCAOfEuXRntZIbckl00XKX9qAIN"
  navigation:
    success_url: "https://start-dev.gogettested.com/appointment/{}/pay/success?token={}"
    cancel_url: "https://start-dev.gogettested.com"
    vax_success_url: "https://start-dev.gogettested.com/vaxyes/register/callback?{}"
    vax_cancel_url: "https://start-dev.gogettested.com"

image_urls:
  flu_shot:
    - 'http://ggt-image-server.com/flu' # Add a URL of a stock photo or S3 bucket
  payment:
    - 'https://goget-static-content.s3.us-east-2.amazonaws.com/ggtlogo.png' # Add a URL of a stock photo or S3 bucket
  vax:
    - 'https://goget-static-content.s3.us-east-2.amazonaws.com/ggv_icon.png'

applewallet:
  host: dev.api.gogettested.com
  path: /api/vax_wallet_pass_apple_upadte

lab_integrations:
  s3_bucket: ggt-sftp-dev
  archive_bucket: ggt-sftp-archive-dev
  labreport_bucket: ggt-labreports-dev
  outbound_file_prefix: ggt-outbound

  MAWD:
    outbound_path: mawdpath/prod/orders/
    inbound_path: mawdpath/prod/results/
    inbound_data_table_name: mawdpath_inbound_data

  AIT:
    outbound_path: healthtrackrx_merth/prod/orders/
    inbound_path: healthtrackrx/Reports/
    inbound_data_table_name: healthtrackrx_inbound_data

  CRL:
    outbound_path: DOES_NOT_EXIST
    inbound_path: crllabs/prod/results/
    inbound_data_table_name: crl_inbound_data
    api_username: WELLHEALTH
    api_password: 38cvZtg4v8
    api_url: https://api.crlclear.com/order

  CHOPO:
    outbound_path: chopolabs/prod/orders/
    inbound_path: chopolabs/prod/results
    inbound_data_table_name: chopo_inbound_data

  LAB3A:
    outbound_path: lab3a/prod/orders/
    inbound_path: lab3a/prod/results
    inbound_data_table_name: lab3a_inbound_data

# Define feature flags here
features:
  vax_yes_payment: true