#Common
STATUS = 'status'
SUCCESS = 'success'
FAILED = 'failed'
INFO = 'info'
ERROR = 'error'
NOT_FOUND = 'Not Found'
DESCRIPTION = 'description'

BACKGROUND_TASK_INITIATE_MESSAGE = 'Background Task Initiated'

DEFAULT_GROUP_CODE = '_DEFAULT_'

#Service Catalog
SERVICE_CODE_COVID19_TEST = 'COVID_19_TEST'
SERVICE_CODE_FLU_SHOT = 'FLU_SHOT'
SERVICE_CODE_CONSULT = 'CONSULT'
<<<<<<< HEAD
CLINICAL_PROVIDER_RT_TAG = 'Clinical Provider App'
PATIENT_RT_TAG = 'Patient Front End'
BACKGROUND_TASK_RT_TAG = 'Background Tasks'
ADMIN_PORTAL_RT_TAG = 'Admin Portal'
CONTACT_CENTER_RT_TAG = 'Contact Center App'
PRINTER_HUB_RT_TAG = 'Printer Hub'
AUTH_FAILED_MESSAGE = 'Not Authorized'
CARE_PROVIDER_RT_TAG = 'Care Provider'
BILLER_APP_TAG = 'Biller App'
=======

#Auth
AUTH_FAILED_MESSAGE = "Not Authorized"
CLINICAL_PROVIDER_RT_TAG = "Clinical Provider App"
PATIENT_RT_TAG = "Patient Front End"
BACKGROUND_TASK_RT_TAG = "Background Tasks"
ADMIN_PORTAL_RT_TAG = "Admin Portal"
CONTACT_CENTER_RT_TAG = "Contact Center App"
PRINTER_HUB_RT_TAG = "Printer Hub"
CARE_PROVIDER_RT_TAG = "Care Provider"
BILLER_APP_TAG = "Biller App"

#Appointment
APPOINTMENT_STATUS_SCHEDULED = 'scheduled'
APPOINTMENT_STATUS_CHECKED_IN = 'checked_in'
APPOINTMENT_STATUS_TEST_IN_PROGRESS = 'test_in_progress'
APPOINTMENT_STATUS_VIAL_SCANNED = 'vial_scanned'
APPOINTMENT_STATUS_TEST_COMPLETED = 'test_completed'

APPOINTMENT_ACTION_CHECK_IN = 'check_in'
APPOINTMENT_ACTION_START_TEST = 'start_test'
APPOINTMENT_ACTION_SCAN_VIAL = 'scan_vial'
APPOINTMENT_ACTION_END_TEST = 'end_test'
APPOINTMENT_ACTION_NONE = ''
>>>>>>> 95635f8622d9fe5c7f614de8381283c4343c1ad6
