# Common
STATUS = 'status'
SUCCESS = 'success'
FAILED = 'failed'
INFO = 'info'
WARNING = 'warning'
ERROR = 'error'
NOT_FOUND = 'Not Found'
DESCRIPTION = 'description'
REASON_CODE = 'reason_code'

BACKGROUND_TASK_INITIATE_MESSAGE = 'Background Task Initiated'

DEFAULT_GROUP_CODE = '_DEFAULT_'

Environment_DEV_2 = 'dev2'
Environment_DEV = 'dev'
Environment_QA = 'qa'
Environment_PROD = 'prod'

# Service Catalog
SERVICE_CODE_COVID19_TEST = 'COVID_19_TEST'
SERVICE_CODE_COVID19_TEST_NV = 'COVID_19_TEST_NV'
SERVICE_CODE_COVID19_TEST_MEXICO = 'COVID_19_TEST_MEXICO'
SERVICE_CODE_COVID19_TEST_ANTIGEN = 'COVID_19_TEST_ANTIGEN'
SERVICE_CODE_COVID19_TEST_ANTIGEN_NV = 'COVID_19_TEST_ANTIGEN_NV'
SERVICE_CODE_COVID19_TEST_MEXICO_ANTIGEN = 'COVID_19_TEST_MEXICO_ANTIGEN'
SERVICE_CODE_COVID_19_TEST_MX_RESORT = 'COVID_19_TEST_MX_RESORT'
SERVICE_CODE_FLU_SHOT = 'FLU_SHOT'
SERVICE_CODE_CONSULT = 'CONSULT'
SERVICE_CODE_COVID_19_VACCINE_PFIZER_1 = 'COVID_19_VACCINE_PFIZER_1'
SERVICE_CODE_COVID_19_VACCINE_PFIZER_2 = 'COVID_19_VACCINE_PFIZER_2'
SERVICE_CODE_COVID_19_VACCINE_MODERNA_1 = 'COVID_19_VACCINE_MODERNA_1'
SERVICE_CODE_COVID_19_VACCINE_MODERNA_2 = 'COVID_19_VACCINE_MODERNA_2'
SERVICE_CODE_COVID_19_VACCINE_JNJ = 'COVID_19_VACCINE_JNJ'

# Service Names
SERVICE_TO_NAME_MAP = {
    "COVID_19_TEST": "COVID 19 PCR Test",
    "COVID_19_TEST_MX_RESORT": "COVID 19 PCR Test Mexico Resort",
    "COVID_19_TEST_NV": "COVID 19 PCR Test",
    "COVID_19_TEST_MEXICO": "COVID 19 PCR Test",
    "COVID_19_TEST_ANTIGEN": 'COVID 19 Antigen Test',
    "COVID_19_TEST_ANTIGEN_NV": 'COVID 19 Antigen Test',
    "COVID_19_TEST_MEXICO_ANTIGEN": 'COVID 19 Antigen Test',
    "FLU_SHOT": 'Flue Shot',
    "CONSULT": 'Consultation',
    "COVID_19_VACCINE_PFIZER_1": 'Pfizer dose 01',
    "COVID_19_VACCINE_PFIZER_2": 'Pfizer dose 02',
    "COVID_19_VACCINE_MODERNA_1": 'Moderna dose 01',
    "COVID_19_VACCINE_MODERNA_2": 'Moderna dose 01',
    "COVID_19_VACCINE_JNJ": 'J & J dose'
}

# Route Tags
PAGE_REDIRECTS_RT_TAG = 'Page Redirects'
CLINICAL_PROVIDER_RT_TAG = 'Clinical Provider App'
PATIENT_RT_TAG = 'Patient Front End'
BACKGROUND_TASK_RT_TAG = 'Background Tasks'
ADMIN_PORTAL_RT_TAG = 'Admin Portal'
CONTACT_CENTER_RT_TAG = 'Contact Center App'
PRINTER_HUB_RT_TAG = 'Printer Hub'
REPORT_RT_TAG = 'Reporting'
MANAGEMENT_RT_TAG = 'Management'
CARE_PROVIDER_RT_TAG = 'Care Provider'
BILLING_RT_TAG = 'Billing App'
VENDOR_RT_TAG = 'Vendor Integration'
PAYMENT_RT_TAG = 'Payment Integration'

# API Prefixes
CLINICAL_PROVIDER_PATH_PREFIX = '/api/provider'
PATIENT_PATH_PREFIX = '/api'
BACKGROUND_TASK_PATH_PREFIX = '/api/task'
ADMIN_PORTAL_PATH_PREFIX = '/api/portal'
CONTACT_CENTER_PATH_PREFIX = '/api/cc'
PRINTER_HUB_PATH_PREFIX = '/api/print'
REPORTING_PATH_PREFIX = '/api/report'
MANAGEMENT_PATH_PREFIX = '/api/management'
CARE_PROVIDER_PATH_PREFIX = '/api/care_provider'
BILLING_PATH_PREFIX = '/api/billing'
VENDOR_PATH_PREFIX = '/api/vendor'
PAYMENT_CHECKOUT_PREFIX = '/api/payment'

# Auth
AUTH_FAILED_MESSAGE = 'Not Authorized'

# Appointment
APPOINTMENT_STATUS_SCHEDULED = 'scheduled'
APPOINTMENT_STATUS_CHECKED_IN = 'checked_in'
APPOINTMENT_STATUS_TEST_IN_PROGRESS = 'test_in_progress'
APPOINTMENT_STATUS_VIAL_SCANNED = 'vial_scanned'
APPOINTMENT_STATUS_TEST_COMPLETED = 'test_completed'
APPOINTMENT_STATUS_TEST_FINALIZED = 'test_finalized'
APPOINTMENT_STATUS_INSURANCE_PENDING = 'insurance_pending'
APPOINTMENT_STATUS_INSURANCE_COLLECTED = 'insurance_collected'
APPOINTMENT_STATUS_NO_INSURANCE = 'no_insurance'

APPOINTMENT_ACTION_START_VAX = 'start_vax'
APPOINTMENT_ACTION_NOTES_VAX = 'notes'
APPOINTMENT_ACTION_END_VAX = 'end_vax'
APPOINTMENT_ACTION_SCAN_VIAL_VAX = 'scan_vial_vax'
APPOINTMENT_ACTION_VERIFY_INSURANCE = 'verify_insurance'
APPOINTMENT_ACTION_COLLECT_INSURANCE = 'collect_insurance'

APPOINTMENT_ACTION_CHECK_IN = 'check_in'
APPOINTMENT_ACTION_CONFIRM_INSURANCE_STATUS = 'confirm_insurance_status'
APPOINTMENT_ACTION_START_TEST = 'start_test'
APPOINTMENT_ACTION_SCAN_VIAL = 'scan_vial'
APPOINTMENT_ACTION_END_TEST = 'end_test'
APPOINTMENT_ACTION_REPRINT = 'reprint'
APPOINTMENT_ACTION_ANTIGEN_TEST_RESULTS = 'antigen_results'
APPOINTMENT_ACTION_NONE = ''

# Payment APIs
STRIPE = 'stripe'
VAX_YES_PAYMENT_FLOW = 'vax_yes_payment_flow'
GGT_PAYMENT_FLOW = 'ggt_payment_flow'
