steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
<<<<<<< HEAD
  args: ['-c', 'docker pull gcr.io/ggt-pfe-dev/ggt-pfe-services:latest || exit 0']
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '-t', 'gcr.io/ggt-pfe-dev/ggt-pfe-services:latest',
            '--cache-from', 'gcr.io/ggt-pfe-dev/ggt-pfe-services:latest',
            '.'
        ]
images: ['gcr.io/ggt-pfe-dev/ggt-pfe-services:latest']
=======
  args: ['-c', 'docker pull gcr.io/ggt-pfe-dev2/ggt-pfe-services:latest || exit 0']
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '-t', 'gcr.io/ggt-pfe-dev2/ggt-pfe-services:latest',
            '--cache-from', 'gcr.io/ggt-pfe-dev2/ggt-pfe-services:latest',
            '.'
        ]
images: ['gcr.io/ggt-pfe-dev2/ggt-pfe-services:latest']
>>>>>>> 7f21cdee629ec8bbb25a7266fd00368a48c6639e
